### ISSUE TITLE
Suggestion: document optional driver parameters

### ISSUE THREAD

**Issue by ChrisHardie** [singlequote/laravel-webdav#6]
Short version: would you consider adding some more documentation in the README for what each of the optional driver parameters do? They are a bit mysterious right now, especially `proxy`, `authType` and `encoding`.

Longer version:
I spent a few hours today banging my head against why Storage operations on a webdav disk using this driver were failing silently. I eventually figured out from the [Flysystem error handling docs](https://flysystem.thephpleague.com/docs/usage/exception-handling/) that I could do a `try {} catch() {}` call that caught `League\Flysystem\FilesystemException` exceptions, which led me to the error message "Unable to write file at location: test.jpg. necessary data rewind wasn't possible" which led me to [this Stackoverflow response](https://stackoverflow.com/questions/72365649/necessary-data-rewind-wasnt-possible-with-webdav) which led me to try out setting `authType` to 1, and it worked! But I don't know why and I would have loved to avoided that rabbit hole. I think extended docs here could help others.

Thanks for considering it!

**Comment by wimurk** [comment]
Hi @ChrisHardie,

I have edited the README and added the optional types. Hope this will helpt others.
